### ISSUE TITLE
appfairy_config.js not working

### ISSUE THREAD

**Issue by altechzilla** [DAB0mB/Appfairy#14]
When trying to use a custom config, it won't read the config from the project root. Also, when triggered via the CLI, it says it can't find a path. Any thoughts?

**Comment by DAB0mB** [comment]
You're probably using an absolute path instead o f a relative one. How did you run the command exactly

**Comment by DAB0mB** [comment]
There was a typo in the config name in README.md

**Comment by DAB0mB** [comment]
Should be af_config.js
