### ISSUE TITLE
Interactions don't seem to work after appfairy migration

### ISSUE THREAD

**Issue by crushman1** [DAB0mB/Appfairy#17]
Hello,
I have looked through the two other interaction-related issues and i don't understand them. How **exactly** does one get click interactions working after migrating a Webflow project to React? There is literally no documentation on this...

**Comment by JeffreyYu2018** [comment]
Check out his [Appfairy YouTube tutorial ](https://www.youtube.com/watch?v=6hJe6pZld0o)– he goes through setting up click interactions for a contact form.

**Comment by DAB0mB** [comment]
v0.8.0 is now released and I added support for interactions
