### ISSUE TITLE
Files missing/Error when using appfairy command

### ISSUE THREAD

**Issue by jayb967** [DAB0mB/Appfairy#6]
I keep getting this error message when running the appfairy command: 
`TypeError: Cannot read property 'replace' of undefined
    at replace (/usr/local/lib/node_modules/appfairy/build/webpack:/src/utils/index.js:6:13)
    at escape (/usr/local/lib/node_modules/appfairy/build/webpack:/src/writers/view-writer.js:347:31)
    at Array.map (<anonymous>)
    at ViewWriter.map (/usr/local/lib/node_modules/appfairy/build/webpack:/src/writers/view-writer.js:344:28)
    at ViewWriter.composeScriptsDeclerations (/usr/local/lib/node_modules/appfairy/build/webpack:/src/writers/view-writer.js:275:22)
    at compose (/usr/local/lib/node_modules/appfairy/build/webpack:/src/writers/view-writer.js:258:77)
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/appfairy/build/appfairy.js:604:191)
    at /usr/local/lib/node_modules/appfairy/build/appfairy.js:604:437
    at new Promise (<anonymous>)`

Although it is an Error I still get all of my view files except the home IndexView.js.

I tried installing previous versions with no avail.. Is there something I might need to configure? Let me know if you need me to include my index html file. Thanks!

**Comment by DAB0mB** [comment]
Hey @jayb967, yes please send me the `index.html` file contents, I might need the other files but let's start with that. If you don't feel comfortable sharing it publicly you can send it to me via email.

**Comment by jayb967** [comment]
Appreciate the help! I don't mind if it's a bug that can help someone else. Here is the index.html:
`
<!DOCTYPE html>

<html data-wf-page="5bbfe48c87e732a2a905ac1f" data-wf-site="5bbfe48c87e732613505ac16" lang="en">
<head>
  <meta charset="utf-8">
  <title>title</title>
  <meta content="apparel" name="description">
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <link href="css/normalize.css" rel="stylesheet" type="text/css">
  <link href="css/components.css" rel="stylesheet" type="text/css">
  <link href="css/store.css" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js" type="text/javascript"></script>
  <script type="text/javascript">
      WebFont.load({
        google: {
          families: ["Merriweather:300,300italic,400,400italic,700,700italic,900,900italic", "Open Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic", "Roboto:300,regular,500", "Roboto Slab:100,300,regular", "Roboto Condensed:regular,700"]
        }
      });
    </script>
  
  <script type="text/javascript">
      ! function(o, c) {
        var n = c.documentElement,
          t = " w-mod-";
        n.className += t + "js", ("ontouchstart" in o || o.DocumentTouch && c instanceof DocumentTouch) && (n.className += t + "touch")
      }(window, document);
    </script>
  <link href="images/logo32.jpeg" rel="shortcut icon" type="image/x-icon">
  <link href="images/logo256.jpeg" rel="apple-touch-icon">
</head>
<body class="body">
  <div data-collapse="medium" data-animation="default" data-duration="1000" data-w-id="54e377ad-f5f5-c82a-4279-7fea3c35b6d4" class="navbar w-nav">
    <div class="nav-container w-container">
      <div class="nav-container w-clearfix"><a href="index.html" class="brand-wrapper w-nav-brand w--current"><img src="images/FinalPinkClear.png" width="300" srcset="images/FinalPinkClear-p-500.png 500w, images/FinalPinkClear-p-800.png 800w, images/FinalPinkClear-p-1080.png 1080w, images/FinalPinkClear.png 1101w" sizes="(max-width: 479px) 45vw, (max-width: 991px) 27vw, 11vw" data-w-id="54e377ad-f5f5-c82a-4279-7fea3c35b6d8" alt="" class="image-5"></a>
        <nav role="navigation" class="nav-menu w-clearfix w-nav-menu"><a href="index.html" class="nav-link w-nav-link w--current">HOME</a><a href="shop.html" class="nav-link w-nav-link">shop</a><a href="membership.html" class="nav-link w-nav-link">MEMBership</a><a href="about.html" class="nav-link w-nav-link">About</a><a href="#" class="nav-link w-nav-link">Contact</a><a href="https://store.foxycart.com/cart?cart=view" class="nav-link shadow w-nav-link">Cart(0)</a><a href="membership.html" class="nav-link right button sign-up w-nav-link">become a member</a></nav>
        <div class="menu-button w-nav-button">
          <div class="icon w-icon-nav-menu"></div>
        </div>
      </div>
    </div>
  </div>
  <div data-delay="3000" data-animation="over" data-autoplay="1" data-easing="ease-in-out" data-nav-spacing="8" data-duration="500" data-infinite="1" class="slider w-slider">
    <div class="mask-2 w-slider-mask">
      <div class="slide-5 w-slide">
        <div class="container-2 w-container">
          <h1 class="heading">New Collection</h1>
          <p data-w-id="e24f552c-4b29-8f93-e946-3c441679833e" style="opacity:0" class="paragraph">Shop the latest fashion</p><a href="shop.html" class="button-2 w-button">Shop Now</a></div>
      </div>
      <div class="slide-3 w-slide">
        <div class="container-2 w-container">
          <h1 class="heading">New Collection</h1>
          <p class="paragraph">Shop the latest fashion</p><a href="#" class="button-2 w-button">Shop Now</a></div>
      </div>
      <div class="slide-2 w-slide">
        <div class="container-2 w-container">
          <h1 class="heading">New Collection</h1>
          <p class="paragraph"><em>Premium Delivery Service</em></p><a href="#" class="button-2 w-button">Shop Now</a></div>
      </div>
      <div class="slide-4 w-slide">
        <div class="container-2 w-container">
          <h1 class="heading">New Collection</h1>
          <p class="paragraph">Shop fashion</p><a href="#" class="button-2 w-button">Shop Now</a></div>
      </div>
    </div>
    <div class="w-slider-arrow-left">
      <div class="icon-2 w-icon-slider-left"></div>
    </div>
    <div class="w-slider-arrow-right">
      <div class="icon-3 w-icon-slider-right"></div>
    </div>
    <div class="w-slider-nav w-round"></div>
  </div>
  <div class="section hero">
    <div class="w-container">
      <h1 class="small-heading">THE COLLECTION</h1>
      <h1 class="huge-heading">Heading</h1><a href="membership.html" class="button">GET STARTED NOW</a><a href="#Learn-More" class="outline-button">LEARN MORE</a>
      <div class="image-crop hero top"><img src="images/FinalPinkClear.png" width="480" srcset="images/FinalPinkClear-p-500.png 500w, images/FinalPinkClear-p-800.png 800w, images/FinalPinkClear-p-1080.png 1080w, images/FinalPinkClear.png 1101w" sizes="(max-width: 767px) 92vw, 480px" alt="" class="image-2"></div>
    </div>
  </div>
  <div id="Learn-More" data-w-id="de75ea04-e3db-951e-5494-9bdd2a6e8463" class="section darkestgrey">
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-7 w-col-stack">
          <div data-w-id="420bd3f8-e6b5-2ac9-e858-c2b3322c7758" style="opacity:0" class="image-crop product"></div>
        </div>
        <div class="column-5 w-col w-col-5 w-col-stack">
          <h2 data-w-id="8ef0fc6d-40bf-5a7d-0866-5387347ab8ec" style="opacity:0" class="heading-3">How it works</h2>
          <ul class="feature-list w-list-unstyled">
            <li class="feature-item w-clearfix">
              <div class="feature-icon-wrapper"><img src="images/Blk-4.png" alt="" class="feature-icon"></div>
              <div data-w-id="9013f5e5-9b66-7ddc-3907-190467a6cd9b" style="opacity:0" class="feature-text title">Answer a few brief questions about your interests</div>
              <div data-w-id="8ab5158e-fa9b-9fe2-a7c7-e0efbce77a4a" style="opacity:0" class="feature-text"> Our personal designer will use your preferences to send your monthly subscription box and even make new designs!</div>
            </li>
            <li class="feature-item w-clearfix">
              <div class="feature-icon-wrapper"><img src="images/Black2.png" width="77" srcset="images/Black2-p-500.png 500w, images/Black2-p-800.png 800w, images/Black2-p-1080.png 1080w, images/Black2.png 1170w" sizes="60px" alt="" class="feature-icon"></div>
              <div data-w-id="be2fa4c6-7795-3569-0f11-50ad55502503" style="opacity:0" class="feature-text title">Join Us!</div>
              <div data-w-id="fa22991f-3aab-7305-0f4c-31543862f939" style="opacity:0" class="feature-text">Find a Membership thats perfect for you. Doesn&#x27;t get much sweeter than that..</div>
            </li>
            <li class="feature-item w-clearfix">
              <div class="feature-icon-wrapper"><img src="images/Black1.png" srcset="images/Black1-p-500.png 500w, images/Black1-p-800.png 800w, images/Black1.png 1052w" sizes="57.328125px" alt="" class="feature-icon"></div>
              <div data-w-id="5d479187-50db-838c-7b2f-4c886808d101" style="opacity:0" class="feature-text title">Shop!</div>
              <div data-w-id="a3c9bd19-ca0b-4316-6825-3606deaa3bdb" style="opacity:0" class="feature-text">Find fashion that you want to wear!</div>
            </li>
          </ul>
          <p data-w-id="8204cee6-14f8-0311-0846-81273d784700" style="opacity:0" class="paragraph-4"><strong class="bold-text">MEMBER PERKS:</strong> You&#x27;re guaranteed to feel more confident in wear! &amp; Everyone knows that the better you look and feel the more money you <br>attract and make! <br><br>Not to mention the freebie in your Birthday Shipment + Surprise Accessories EVERY MONTH  Oh yea &amp; It&#x27;s all delivered to your doorstep!<br>Mic Drop*</p>
        </div>
      </div>
    </div>
  </div>
  <div>
    <div class="container-5 w-container">
      <h2 class="small-heading options">Our Pricing is simple</h2>
      <div data-w-id="0300165c-17b3-82e8-cdd5-1a881eced8bc" style="opacity:0" class="div-block-5">
        <h1 class="pricing-header">Option a - $25/month</h1>
        <ul class="unordered-list optionslist">
          <li class="option-a-list-item">25% off outfits</li>
          <li class="option-a-list-item">10% off accessories</li>
          <li class="option-a-list-item">15% custom outfits</li>
          <li class="option-a-list-item">free shipping</li>
          <li class="option-a-list-item">free access to all events</li>
        </ul><a href="membership.html" class="button options w-button">Sign up now</a></div>
      <div data-w-id="6713d05a-2500-1f07-5103-c245081c9c86" style="opacity:0" class="div-block-5 _2nd">
        <h1 class="pricing-header">option b - $85/month</h1>
        <h1 class="pricing-header option-b">2 outfits + 1 money bag</h1>
        <ul class="unordered-list optionslist option-b">
          <li class="option-a-list-item">+ all essentials to secure the bag ( dry hands, body wipeskds nail glue, hair ties, etc..)</li>
          <li class="option-a-list-item">+ everything from option a</li>
          <li class="option-a-list-item">$280/month savings</li>
        </ul><a href="membership.html" class="button options w-button">Sign up now</a></div>
    </div>
    <div class="shop-image-container w-container">
      <div class="shop-image-container">
        <div class="dynamic-wrapper">
          <div class="col">
            <a href="shop.html" class="link-block-5 w-inline-block">
              <div data-w-id="70d33b93-dcb0-12e6-9f5c-720ccddd1fc8" style="opacity:0" class="mansory-div">
                <div class="feature-container-div img1">
                  <h1 class="image-heading">Full Outfits</h1>
                </div>
              </div>
            </a>
            <a href="shop.html" class="link-block-6 w-inline-block">
              <div data-w-id="5c29916c-e7f9-02fe-d923-55c532506ac5" style="opacity:0" class="mansory-div">
                <div class="feature-container-div img2">
                  <h1 class="image-heading">Tops</h1>
                </div>
              </div>
            </a>
          </div>
          <div class="col">
            <a data-w-id="03dc7eb9-5a0f-ffcf-7f5f-5e5657e5a178" style="opacity:0" href="membership.html" class="mansory-div w-inline-block">
              <div class="feature-container-div img3">
                <h1 class="image-heading">shop</h1>
              </div>
            </a>
          </div>
          <div class="col-2">
            <a data-w-id="3ec83e56-fd10-97a7-ac66-3ff10e38f4a2" style="opacity:0" href="membership.html" class="mansory-div w-inline-block">
              <div class="feature-container-div img4">
                <h1 class="image-heading">join now</h1>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="section darkgrey">
    <div class="container-7 w-container">
      <div class="div-block-4">
        <div class="product-slider-div">
          <div class="product-slider-core">
            <div class="product-description">
              <h1 class="heading-4">Wear</h1>
              <p class="paragraph-9">Whether you&#x27;re grinding hard at work or going out to a rave, has a unique mix of clothing! You&#x27;ll be looking hot in our daring selection. Everything you need to secure the bag!$</p>
            </div>
            <div class="product-description-slider-arrows">
              <a href="#" class="arrow-wrapper-product w-inline-block">
                <div class="arrow-back-div"></div>
              </a>
              <a href="#" class="arrow-wrapper-product w-inline-block">
                <div class="arrow-back-div forward"></div>
              </a>
            </div>
          </div>
          <div data-delay="3000" data-animation="slide" data-autoplay="1" data-easing="ease-out" data-duration="700" data-infinite="1" class="slider-2 w-slider">
            <div class="mask w-slider-mask">
              <div class="slide-6 w-slide"><a href="#" class="lightbox-link photo1 w-inline-block w-lightbox"><img src="https://d3e54v103j8qbb.cloudfront.net/img/placeholder-thumb.svg" alt="" class="image"><script type="application/json" class="w-json">{
  "items": [
    {
      "width": 2200,
      "caption": "",
      "height": 3300,
      "fileName": "5bd121297acbd9bafde71356_UB001T & UB001B BACK.jpg",
      "origFileName": "UB001T & UB001B BACK.jpg",
      "url": "images/UB001T--UB001B-BACK_1.jpg",
      "_id": "5bd121297acbd9bafde71356",
      "type": "image",
      "fileSize": 3878215
    }
  ],
  "group": "2"
}</script></a>
                <div class="white-image-layover"></div>
                <div class="product-image-shadow"></div>
              </div>
              <div class="slide-7 w-slide"><a href="#" class="lightbox-link photo2 w-inline-block w-lightbox"><img src="https://d3e54v103j8qbb.cloudfront.net/img/placeholder-thumb.svg" alt="" class="image"><script type="application/json" class="w-json">{
  "items": [
    {
      "width": 1900,
      "caption": "",
      "height": 2850,
      "fileName": "5bc122bf5a68ee8dc81a215a_UB016 FEELIN IT BANDEAU.jpg",
      "origFileName": "UB016 FEELIN IT BANDEAU.jpg",
      "url": "images/UB016-FEELIN-IT-BANDEAU.jpg",
      "_id": "5bc122bf5a68ee8dc81a215a",
      "type": "image",
      "fileSize": 3979704
    }
  ],
  "group": "2"
}</script></a>
                <div class="white-image-layover"></div>
                <div class="product-image-shadow"></div>
              </div>
              <div class="slide-8 w-slide"><a href="#" class="lightbox-link photo3 w-inline-block w-lightbox"><img src="https://d3e54v103j8qbb.cloudfront.net/img/placeholder-thumb.svg" alt="" class="image"><script type="application/json" class="w-json">{
  "items": [
    {
      "type": "image",
      "_id": "5bc120973ef47f8251390ea4",
      "fileName": "5bc120973ef47f8251390ea4_photo.jpg",
      "origFileName": "photo.jpg",
      "width": 6000,
      "height": 4000,
      "fileSize": 1716036,
      "url": "images/photo.jpg"
    }
  ],
  "group": "2"
}</script></a>
                <div class="white-image-layover"></div>
                <div class="product-image-shadow"></div>
              </div>
              <div class="slide-9 w-slide"><a href="#" class="lightbox-link photo4 w-inline-block w-lightbox"><img src="https://d3e54v103j8qbb.cloudfront.net/img/placeholder-thumb.svg" alt="" class="image"><script type="application/json" class="w-json">{
  "items": [],
  "group": "2"
}</script></a>
                <div class="white-image-layover"></div>
                <div class="product-image-shadow"></div>
              </div>
              <div class="slide-10 w-slide"><a href="#" class="lightbox-link photo5 w-inline-block w-lightbox"><img src="https://d3e54v103j8qbb.cloudfront.net/img/placeholder-thumb.svg" alt="" class="image"><script type="application/json" class="w-json">{
  "items": [],
  "group": "2"
}</script></a>
                <div class="white-image-layover"></div>
                <div class="product-image-shadow"></div>
              </div>
              <div class="slide-11 w-slide"><a href="#" class="lightbox-link photo6 w-inline-block w-lightbox"><img src="https://d3e54v103j8qbb.cloudfront.net/img/placeholder-thumb.svg" alt="" class="image"><script type="application/json" class="w-json">{
  "items": [],
  "group": "2"
}</script></a>
                <div class="white-image-layover"></div>
                <div class="product-image-shadow"></div>
              </div>
            </div>
            <div class="left-arrow w-slider-arrow-left">
              <div class="w-icon-slider-left"></div>
            </div>
            <div class="right-arrow w-slider-arrow-right">
              <div class="w-icon-slider-right"></div>
            </div>
            <div class="w-slider-nav w-round"></div>
          </div>
        </div>
      </div>
      <div class="w-row">
        <div class="column-4 w-col w-col-5">
          <h3 class="heading-6">FIRST &amp; ONLY AFFORDABLE SUBSCRIPTION SERVICE FOR ALL YOUR WEAR NEEDS</h3>
          <p class="paragraph-8"><strong class="bold-text-2">trendy wear that is edgy, sexy, affordable, and comfortable. wants you to look great day and night, work or play, whatever the occasion. We want every visit to our custom shop to feel like you are exploring your most sultry yet stylish inner self! <br></strong><br>It&#x27;s Simple: We Ship Monthly Concierge Subscription Boxes Right to your doorstep!  Anywhere In The Continental US For FREE. <br>No Kidding.</p>
        </div>
        <div class="image-column w-col w-col-7">
          <div class="image-crop iphone"><img src="images/Blk-4.png" width="281" alt="" class="iphone-image"></div>
        </div>
      </div>
    </div>
  </div>
  <div class="section press">
    <div class="container-3 w-container">
      <div id="w-node-e631d7cccab4-a905ac1f" class="press-image-wrapper"><img src="images/image.png" data-w-id="700e0346-8389-6ca8-8827-5852dac462bd" alt="" class="press-logo">
        <div class="clothing-type">WEAR</div>
      </div>
      <div id="w-node-0314fd2701ac-a905ac1f" class="press-image-wrapper"><img src="images/noun_Heart-Hands_433984_FFFFFF.png" srcset="images/noun_Heart-Hands_433984_FFFFFF-p-500.png 500w, images/noun_Heart-Hands_433984_FFFFFF-p-800.png 800w, images/noun_Heart-Hands_433984_FFFFFF-p-1080.png 1080w, images/noun_Heart-Hands_433984_FFFFFF.png 1200w" sizes="(max-width: 479px) 100px, (max-width: 767px) 13vw, 100px" data-w-id="cfc00420-3c41-fb72-596a-e1ad2ec1f4fd" alt="" class="press-logo">
        <div class="clothing-type">festival wear</div>
      </div>
      <div id="w-node-b86b60f42518-a905ac1f" class="press-image-wrapper"><img src="images/BottleServiceWhite.png" alt="" class="press-logo">
        <div class="clothing-type">bottle service &amp;<br> waitress attire</div>
      </div>
      <div id="w-node-69bb68b93cf6-a905ac1f" class="press-image-wrapper"><img src="images/noun_Sewing-Machine_415137_FFFFFF.png" srcset="images/noun_Sewing-Machine_415137_FFFFFF-p-500.png 500w, images/noun_Sewing-Machine_415137_FFFFFF-p-800.png 800w, images/noun_Sewing-Machine_415137_FFFFFF.png 1200w" sizes="(max-width: 479px) 100px, (max-width: 767px) 13vw, 100px" alt="" class="press-logo">
        <div class="clothing-type">custom designs</div>
      </div>
    </div>
  </div>
  <div class="no-pad-section">
    <div class="w-row">
      <div class="padded-column picture w-col w-col-6"></div>
      <div class="padded-column w-col w-col-6">
        <div class="width-limiter">
          <h2 class="_24hour-heading">24/7 Email Support</h2>
          <p>If you have any issues, we will always contact you within 24 hours. </p><a href="contact.html" class="get-started-link simple gray">get support now</a></div>
      </div>
    </div>
  </div>
  <div class="section sign-up">
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-8">
          <h2 class="sign-up-title">Start Your journey today!</h2>
          <div class="subtitle pricing">Receiving custom tailored monthly is so much better at up to 25% off!</div>
        </div>
        <div class="sign-up-column w-col w-col-4"><a href="membership.html" class="button">SIGN UP TODAY   ❯</a></div>
      </div>
    </div>
  </div>
  <div class="section footer">
    <div class="w-container">
      <div class="w-row">
        <div class="footer-column w-col w-col-3">
          <h4>COMPANY</h4>
          <ul class="w-list-unstyled">
            <li><a href="#" class="footer-link">Home</a></li>
            <li><a href="about.html" class="footer-link">About</a></li>
            <li><a href="shop.html" class="footer-link">Shop</a></li>
            <li><a href="membership.html" class="footer-link">Membership</a></li>
          </ul>
        </div>
        <div class="footer-column w-col w-col-3">
          <h4>get help</h4>
          <ul class="w-list-unstyled">
            <li><a href="contact.html" class="footer-link">Contact Us</a></li>
            <li><a href="shipping-returns.html" class="footer-link">Shipping &amp; Returns</a></li>
            <li><a href="termsconditions.html" class="footer-link">Terms &amp; Conditions</a></li>
          </ul>
        </div>
        <div class="footer-column w-col w-col-3"></div>
        <div class="footer-column w-col w-col-3">
          <div class="w-form">
            <form name="email-form" data-name="Email Form" class="w-clearfix"><input type="text" name="email" data-name="Email" placeholder="Your email" maxlength="256" required="" class="field-left w-input"><input type="submit" data-wait="Wait..." wait="Wait..." value="OK" class="button form w-button">
              <div class="no-spam">We send about 1-2 emails a month</div>
            </form>
            <div class="success-message w-form-done">
              <p>Thank you! You&#x27;ll be receiving some awesome emails!</p>
            </div>
            <div class="w-form-fail">
              <p>Oops! Something went wrong while submitting the form :(</p>
            </div>
          </div>
          <div><a href="http://www.facebook.com/webflow" class="social-link w-inline-block"><img src="images/twitter-icon.svg" alt=""></a><a href="http://www.facebook.com/webflow" class="social-link w-inline-block"><img src="images/facebook-icon.svg" alt=""></a></div><img src="images/FinalPinkClear.png" width="116" srcset="images/FinalPinkClear-p-500.png 500w, images/FinalPinkClear-p-800.png 800w, images/FinalPinkClear-p-1080.png 1080w, images/FinalPinkClear.png 1101w" sizes="116px" alt="" class="image-3"></div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" type="text/javascript" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="js/webflowproject.js" type="text/javascript"></script>
  
  
  <script data-cfasync="false" src="https://cdn.foxycart.com/store/loader.js" async="" defer=""></script>
  
</body>
</html>

`

**Comment by DAB0mB** [comment]
Hey @jayb967, may I ask for the entire zip file? It would be much easier for me this way. You can send it to me via email and I'll keep complete secrecy over your project.

**Comment by jayb967** [comment]
ok email sent. Thanks!

**Comment by DAB0mB** [comment]
@jayb967 Fixed! There were inline script tags which weren't JavaScript related and I didn't handle that. Accordingly I have released a new version 0.7.2. Enjoy!

**Comment by Neuralquant-Inc** [comment]
Hello @DAB0mB! I am not sure if you will see this, but thank you for making this program. I just found it in the Webflow forums as I've been learning React. I am getting the following error that seems really similar to the issue in this ticket, but slightly different. Below is the error I am getting when I try to run the appfairy command after getting everything set up.

 Could you help me out? I really want to use your program as it will save me a lot of time.

![Error](https://user-images.githubusercontent.com/53234337/69512451-f39c3380-0ef8-11ea-8547-b033ede93fed.PNG)
